apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "spring.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "spring.name" . }}
    helm.sh/chart: {{ include "spring.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "spring.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "spring.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: {{ .Values.context }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbeinitialDelaySeconds }}
            httpGet:
              path: {{ .Values.context }}/actuator/health
              port: http
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbeinitialDelaySeconds }}
            httpGet:
              path: {{ .Values.context }}/actuator/health
              port: http
