apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "spring.name" . }}
    helm.sh/chart: {{ include "spring.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- toYaml .Values.environmentData | indent 2 }}
