{{- $fullName := include "spring.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "spring.name" . }}
    helm.sh/chart: {{ include "spring.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: {{ .Values.context }}
    # kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - {{ .Values.host | quote }}
#      secretName: {{ .secretName }}
  rules:
    - host: {{ .Values.host | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
